# Generated by Django 3.2.11 on 2023-01-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jobsappliedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsappliedto',
            name='employer_logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
