# Generated by Django 3.2.11 on 2023-01-30 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_jobsappliedto_employer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsappliedto',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
            preserve_default=False,
        ),
    ]
