# Generated by Django 3.2.11 on 2023-01-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_jobsappliedto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsappliedto',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='jobsappliedto',
            name='posting_id',
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='employer_website',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_city',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_country',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_employment_type',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_id',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_is_remote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_posted_at_datetime_utc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_publisher',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='job_state',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='receivedInterview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobsappliedto',
            name='receivedOffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobsappliedto',
            name='employer_logo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='jobsappliedto',
            name='employer_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobsappliedto',
            name='job_apply_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='jobsappliedto',
            name='job_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
